import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import OurIdeas from '../components/About/OurIdeas';
import Testimonials from '../components/About/Testimonials';

const About: React.FC = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>Lezada - About</title>
            </Head>

            <section id="breadcrumb">
                <div className="container h-100">
                    <div className="content h-100">
                        <h1>About</h1>
                        <ul className="breadcrumb-links d-flex">
                            <li>
                                <Link href="/">
                                    <a>Home</a>
                                </Link>
                            </li>
                            <li>
                                <span>About</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <OurIdeas />
            <Testimonials />
        </>
    )
};

export default About;