import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import CartTable from '../components/Cart/CartTable';
import CartTotals from '../components/Cart/CartTotals';

const Cart: React.FC = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>Lezada - Cart</title>
            </Head>

            <section id="breadcrumb">
                <div className="container h-100">
                    <div className="content h-100">
                        <h1>Cart</h1>
                        <ul className="breadcrumb-links d-flex">
                            <li>
                                <Link href="/">
                                    <a>Home</a>
                                </Link>
                            </li>
                            <li>
                                <span>Cart</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <section id="cart-content">
                <div className="container">
                    <div className="row">
                        <div className="col-12">
                            <CartTable />
                        </div>
                    </div>
                    <div className="row">
                        <div className="col-lg-5 offset-lg-7">
                            <CartTotals />
                        </div>
                    </div>
                </div>
            </section>
        </>
    )
};

export default Cart;