import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import CartTable from '../components/Cart/CartTable';
import CartTotals from '../components/Cart/CartTotals';
import { MdShoppingCart } from 'react-icons/md';
import { useSelector } from 'react-redux';
import { RootState } from '../redux/reducers';

const Cart: React.FC = () => {
    const cartState = useSelector((state: RootState) => state.cart);
    const cart = cartState.cart;

    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>Lezada - Cart</title>
            </Head>

            <section id="breadcrumb">
                <div className="container h-100">
                    <div className="content h-100">
                        <h1>Cart</h1>
                        <ul className="breadcrumb-links d-flex">
                            <li>
                                <Link href="/">
                                    <a>Home</a>
                                </Link>
                            </li>
                            <li>
                                <span>Cart</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <section id="cart-content">
                <div className="container">
                    {
                        cart.length > 0 ? (
                            <>
                                <div className="row">
                                    <div className="col-12">
                                        <CartTable cart={cart} />
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-lg-5 offset-lg-7">
                                        <CartTotals cart={cart} />
                                    </div>
                                </div>
                            </>
                        ) : (
                            <div className="row">
                                <div className="col-12">
                                    <>
                                        <div className="empty-alert-wrapper text-center">
                                            <div className="icon-and-text">
                                                <span><MdShoppingCart /></span>
                                                <p className="text-muted my-4">No items found in cart</p>
                                            </div>
                                            <div className="back-to-shop-link">
                                                <Link href="/Shop">
                                                    <a className="d-flex align-items-center">Shop Now</a>
                                                </Link>
                                            </div>
                                        </div>
                                    </>
                                </div>
                            </div>
                        )
                    }
                </div>
            </section>
        </>
    )
};

export default Cart;