import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { HiArrowNarrowLeft } from 'react-icons/hi';
import { useSelector, useDispatch } from 'react-redux';
import { MakePaymentSuccess } from '../redux/actions/primaryActions';
import { ClearCart } from '../redux/actions/cartActions';
import { RootState } from '../redux/reducers';
import { IProducts } from '../types/types';

const Checkout: React.FC = () => {
    const cartState = useSelector((state: RootState) => state.cart);
    const primaryState = useSelector((state: RootState) => state.primary);
    const cart = cartState.cart;
    const success = primaryState.paymentSuccess;
    const [loading, setLoading] = useState<boolean>(false);
    const dispatch = useDispatch();

    const totalPrice = cart.reduce((total: number, product: IProducts) => (total += product.price), 0);

    const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
        setLoading(true);
        dispatch(MakePaymentSuccess(true));
        
        setTimeout(() => {
            dispatch(ClearCart());
            setLoading(false);
        }, 1500);
    };

    return (
        <div>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>Lezada - Checkout</title>
            </Head>

            <section id="breadcrumb">
                <div className="container h-100">
                    <div className="content h-100">
                        <h1>Checkout</h1>
                        <ul className="breadcrumb-links d-flex">
                            <li>
                                <Link href="/">
                                    <a>Home</a>
                                </Link>
                            </li>
                            <li>
                                <span>Checkout</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <div className="checkout-content">
                <div className="container">
                    {
                        loading ? (
                            <p>Loading...</p>
                        ) : (
                            <>
                                {
                                    success ? (
                                        <div className="row">
                                            <div className="col-lg-8 offset-lg-2">
                                                <div className="payment-success">
                                                    <div className="text">
                                                        <h5>Thank you! Your order is processing.</h5>
                                                        <p>Your order number is <strong>123</strong></p>
                                                        <p>
                                                            An email will be sent containing information about your purchase.
                                                            If you have any questions about your purchase, email us at
                                                        </p>
                                                    </div>
                                                    <div className="back-to-shop-btn">
                                                        <Link href="/Shop">
                                                            <a className="d-flex align-items-center">
                                                                <span><HiArrowNarrowLeft /></span>
                                                                <p className="m-0">Back to Shop</p>
                                                            </a>
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    ) : (
                                        <form onSubmit={handleSubmit}>
                                            <div className="row">
                                                <div className="col-lg-7">
                                                    {/* ===== billing address ===== */}
                                                    <div className="billing-address">
                                                        <div className="row">
                                                            <div className="col-12">
                                                                <div className="title">
                                                                    <h5>Billing Address</h5>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div className="row">
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="First Name *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Last Name *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Email *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Phone *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-12">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Company *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-12">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Address *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Country *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Town/City *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="State *"
                                                                    />
                                                                </div>
                                                            </div>
                                                            <div className="col-lg-6 col-md-6">
                                                                <div className="inputs-wrapper w-100">
                                                                    <input
                                                                        type="text"
                                                                        className="error-border"
                                                                        placeholder="Zip Code *"
                                                                    />
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="col-lg-5">
                                                    {/* ===== cart totals and orders ===== */}
                                                    <div className="cart-totals-area">
                                                        <div className="title">
                                                            <h5>Cart Totals</h5>
                                                        </div>
                                                        <div className="cart-totals-and-orders">
                                                            <div className="top d-flex justify-content-between">
                                                                <h6>Product</h6>
                                                                <h6>Total</h6>
                                                            </div>
                                                            <div className="body">
                                                                <ul>
                                                                    {
                                                                        cart.map((product: IProducts) => (
                                                                            <li key={product.id} className="d-flex justify-content-between">
                                                                                <div className="left">
                                                                                    <Link href={`/product-details/${product.id}`}>
                                                                                        <a>
                                                                                            <p className="title">{product.title}</p>
                                                                                            <p className="count text-muted">
                                                                                                Quantity:
                                                                                                <span> 1</span>
                                                                                            </p>
                                                                                        </a>
                                                                                    </Link>
                                                                                </div>
                                                                                <div className="right d-flex">
                                                                                    <span>$</span>
                                                                                    <p>{product.price.toFixed(2)}</p>
                                                                                </div>
                                                                            </li>
                                                                        ))
                                                                    }
                                                                </ul>
                                                            </div>
                                                            <div className="bottom">
                                                                <div className="subtotal d-flex justify-content-between">
                                                                    <h6>Sub Total</h6>
                                                                    <div className="price d-flex">
                                                                        <span>$</span>
                                                                        <p>{totalPrice.toFixed(2)}</p>
                                                                    </div>
                                                                </div>
                                                                <div className="total d-flex justify-content-between align-items-center">
                                                                    <h6>Grand Total</h6>
                                                                    <div className="price d-flex">
                                                                        <span>$</span>
                                                                        <p>{totalPrice.toFixed(2)}</p>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div className="order-btn">
                                                            <button type="submit">Place Order</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    )
                                }
                            </>
                        )
                    }
                </div>
            </div>
        </div>
    )
};

export default Checkout;