import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import ContactDetail from '../components/Contact/ContactDetail';
import Map from '../components/Contact/Map';
import GetInTouch from '../components/Contact/GetInTouch';

const Contact: React.FC = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <title>Lezada - Contact</title>
            </Head>

            <section id="breadcrumb">
                <div className="container h-100">
                    <div className="content h-100">
                        <h1>Contact</h1>
                        <ul className="breadcrumb-links d-flex">
                            <li>
                                <Link href="/">
                                    <a>Home</a>
                                </Link>
                            </li>
                            <li>
                                <span>Contact</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </section>

            <ContactDetail />
            <Map />
            <GetInTouch />
        </>
    )
};

export default Contact;