import Head from 'next/head';

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Lezada - Home</title>
      </Head>
    </div>
  )
};

export default Home;