import Head from 'next/head';
import EntrySlider from '../components/Home/EntrySlider';
import Products from '../components/Home/Products';
import Advantages from '../components/Home/Advantages';

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Lezada - Home</title>
      </Head>

      <EntrySlider />
      <Products />
      <Advantages />
    </>
  )
};

export default Home;